name: Deploye Nodejs Application to digital ocean

on:
  push:
    branches:
      - main

jobs:
  deploye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/FULLSTACK-PROJECT1-NINJA/pathifyy-backend
            git pull
            cd infra/
            docker compose down
            docker compose up --build -d
