apiVersion: v1
kind: Pod # This line specifies the object is a Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: nginx
      resources:
        requests:
          cpu: 200m
        limits:
          cpu: 500m
      ports:
        - containerPort: 80
