apiVersion: v1
data:
  APP_NAME: c3Ryb25nUGFzcw==
kind: Secret
metadata:
  creationTimestamp: "2026-04-01T12:34:44Z"
  name: demo-sec
  namespace: default
  resourceVersion: "747"
  uid: 1bc53bc2-eb59-4123-9ca2-65e9cd37101e
type: Opaque
